### ISSUE TITLE
Define and document system and integration test bed components and design

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#13]
Define the components and design of the test bed such as simulators, injectors and other systems involved. Document the test bed details such as components, topology , flows etc.

**Comment by devendrasinghrawat** [comment]
Hi Balaji,

We (Infosys) would like to contribute in system & integration testing area of the Nephio.
Can you please indicate how to proceed?

Regards,
Devendra

**Comment by electrocucaracha** [comment]
@gvbalaji @aravind254 @devendrasinghrawat maybe we should set some time to discuss ideas

**Comment by devendrasinghrawat** [comment]
hi @electrocucaracha, @gvbalaji & @aravind254 i am available 9 AM - 5 PM Indian Standard Time for a discussion. please indicate when (& how) can we meet?

**Comment by electrocucaracha** [comment]
> hi @electrocucaracha, @gvbalaji & @aravind254 i am available 9 AM - 5 PM Indian Standard Time for a discussion. please indicate when (& how) can we meet?

@devendrasinghrawat most of us are in PST, so maybe something around 7:30am(IST)/7pm(PST) can work for everyone

**Comment by devendrasinghrawat** [comment]
@electrocucaracha this sounds good.

**Comment by gvbalaji** [comment]
Hi @devendrasinghrawat , thanks a lot for offering to work on Nephio.  Appreciate that. Sorry missed the email notification on this. 

To get started please join the slack channel if you and your team haven't already.

https://join.slack.com/t/nephio/shared_invite/zt-1e33io92d-fxU272t_CKE8bryUlgDP2A

In addition there are many meetings going on  You can subscribe to these calendars
https://lists.nephio.org/g/sig-automation/calendar
https://lists.nephio.org/g/sig-release/calendar
https://lists.nephio.org/g/sig-netarch/calendar

For the system and integration testing both sig-release and sig-automation groups are involved. Hence please join both the slack channels. 

This is the youtube channel for the project. There is a playlist for getting started as well. 

https://www.youtube.com/channel/UC6pPQlQG5Cnn4PC2KZcnFIQ

Let's get started with these and hope to see  meet you soon on slack. Thanks.

**Comment by johnbelamaric** [comment]
Let's treat this as part of the documentation https://github.com/nephio-project/nephio/issues/159 as it is the same as for the sandbox environment.

**Comment by johnbelamaric** [comment]
closing in favor of https://github.com/nephio-project/nephio/issues/159
