### ISSUE TITLE
Epic : Setup test bed for integration and system tests

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#14]
Set up test infrastructure for integration and system tests based on scope and design.
Refer to https://github.com/nephio-project/sig-release/issues/14 for details.

- [x] #30
- [x] #31
- [ ]

**Comment by radoslawc** [comment]
Hi @gvbalaji I'd like to volunteer myself to help with this one and https://github.com/nephio-project/sig-release/issues/15 as well as other CI/CD related tasks.

**Comment by gvbalaji** [comment]
thanks @radoslawc . Added you as one of the Assignees.  I think @aravind254 will coordinate overall efforts.

**Comment by radoslawc** [comment]
Great, thanks!
