### ISSUE TITLE
Define  scheme for release versioning and release Cycle

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#16]
Define the scheme for release versioning and cycles and document them. We need to define

- Release Cadence ( How often we need to make a release? )
- What is the k8s version to test and support
- Length of support for a release
- Versioning scheme (x.y.z) 
- Hot fixes/back porting mechanism

**Comment by gvbalaji** [comment]
Mention this to TSC and get the versioning scheme.  General sentiment is to version R1 as 0.1.0.

**Comment by johnbelamaric** [comment]
Bala has raised discussion in TSC Slack

**Comment by gvbalaji** [comment]
Tags for
-- Go repos. ( GO convention and Release Tag)
-- Package repos ( Package convention and Release Tag)
