### ISSUE TITLE
Set up Nephio cloud as test environment

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#30]
Nephio Cloud as target test environment

- cluster and network topology
- set up of IP address pools for each clusters
- VLAN for secondary interface segregation
- continuous running test environment (for two weeks before release) on Google cloud (Nephio account)
- IP address assignment to externally accessible service (such as EdgeWatcher)

**Comment by electrocucaracha** [comment]
For now, we have implemented two different approaches in [test-infra project](https://github.com/nephio-project/test-infra).
* [ONE summit approach](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/gce_run.sh#L59-L63) (Enabled) - Deploys a 'static' management and workload infrastructure with Ansible playbooks created in the [ONE summit repo](https://github.com/nephio-project/one-summit-22-workshop/tree/main/nephio-ansible-install). This approach has been tested, but eventually will be deprecated.
* [Cluster API approach](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/gce_run.sh#L53-L57) (Disabled) - Deploys the management cluster only and workloads will be requested as Cluster API CRs. There is work on progress on this approach.

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/test-infra/tree/main/e2e/provision#quick-start-for-gce
