### ISSUE TITLE
Configure PROW infrastructure with all the different plugin(s) labels

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#5]
We need to configure Prow infrastructure to be aware of and take actions based on labels such as lgtm, donotmerge etc.

## Todo
- [x] #6
- [x] #7

**Comment by radoslawc** [comment]
CLA is ready, as well as other labels needed to have PROW working with repositories.
PROW configuration available at: https://github.com/nephio-project/test-infra
