### ISSUE TITLE
Configure  Prow infrastructure to be sensitive to CLAs

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#7]
Configure Prow infrastructure to make sure CLA ( either ICLA or CCLA) is signed prior to contributions.

**Comment by johnbelamaric** [comment]
LF is working on implementing EasyCLA, you may want to coordinate with @lucyhyde on this.

**Comment by aravind254** [comment]
Easy CLA is already enabled for Nephio Project. Lets use this issue to enable PROW to add CLA labels.

**Comment by radoslawc** [comment]
I'have it done in lab, needs some testing, @gvbalaji please assign that one to me, thanks!

**Comment by radoslawc** [comment]
CLA is ready, as well as other labels needed to have PROW working with repositories.
PROW configuration available at: https://github.com/nephio-project/test-infra
